import { z } from 'zod';
export declare const envSchema: z.ZodObject<{
    NODE_ENV: z.ZodDefault<z.ZodEnum<["development", "test", "production"]>>;
    PORT: z.ZodDefault<z.ZodNumber>;
    WEB_PORT: z.ZodDefault<z.ZodNumber>;
    API_BASE_URL: z.ZodDefault<z.ZodString>;
    FRONTEND_URL: z.ZodDefault<z.ZodString>;
    DATABASE_URL: z.ZodDefault<z.ZodString>;
    REDIS_URL: z.ZodDefault<z.ZodString>;
    REDIS_HOST: z.ZodDefault<z.ZodString>;
    REDIS_PORT: z.ZodDefault<z.ZodNumber>;
    REDIS_PASSWORD: z.ZodOptional<z.ZodString>;
    JWT_SECRET: z.ZodDefault<z.ZodString>;
    JWT_EXPIRES_IN: z.ZodDefault<z.ZodString>;
    JWT_REFRESH_SECRET: z.ZodDefault<z.ZodString>;
    JWT_REFRESH_EXPIRES_IN: z.ZodDefault<z.ZodString>;
    COOKIE_SECRET: z.ZodDefault<z.ZodString>;
    INSTAGRAM_TOKEN_ENCRYPTION_KEY: z.ZodDefault<z.ZodString>;
    META_APP_ID: z.ZodDefault<z.ZodString>;
    META_APP_SECRET: z.ZodDefault<z.ZodString>;
    META_GRAPH_API_VERSION: z.ZodDefault<z.ZodString>;
    META_GRAPH_API_BASE_URL: z.ZodDefault<z.ZodString>;
    META_OAUTH_REDIRECT_URI: z.ZodDefault<z.ZodString>;
    META_WEBHOOK_VERIFY_TOKEN: z.ZodDefault<z.ZodString>;
    META_WEBHOOK_SECRET: z.ZodDefault<z.ZodString>;
    META_INSTAGRAM_SCOPES: z.ZodDefault<z.ZodString>;
    AI_DEFAULT_PROVIDER: z.ZodDefault<z.ZodEnum<["gemini", "openai", "gemini_live"]>>;
    GEMINI_API_KEY: z.ZodOptional<z.ZodString>;
    GEMINI_MODEL: z.ZodDefault<z.ZodString>;
    GEMINI_LIVE_WS_ENDPOINT: z.ZodOptional<z.ZodString>;
    OPENAI_API_KEY: z.ZodOptional<z.ZodString>;
    OPENAI_MODEL: z.ZodDefault<z.ZodString>;
    RATE_LIMIT_TTL: z.ZodDefault<z.ZodNumber>;
    RATE_LIMIT_LIMIT: z.ZodDefault<z.ZodNumber>;
    WEBHOOK_RATE_LIMIT_LIMIT: z.ZodDefault<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    NODE_ENV: "development" | "test" | "production";
    PORT: number;
    WEB_PORT: number;
    API_BASE_URL: string;
    FRONTEND_URL: string;
    DATABASE_URL: string;
    REDIS_URL: string;
    REDIS_HOST: string;
    REDIS_PORT: number;
    JWT_SECRET: string;
    JWT_EXPIRES_IN: string;
    JWT_REFRESH_SECRET: string;
    JWT_REFRESH_EXPIRES_IN: string;
    COOKIE_SECRET: string;
    INSTAGRAM_TOKEN_ENCRYPTION_KEY: string;
    META_APP_ID: string;
    META_APP_SECRET: string;
    META_GRAPH_API_VERSION: string;
    META_GRAPH_API_BASE_URL: string;
    META_OAUTH_REDIRECT_URI: string;
    META_WEBHOOK_VERIFY_TOKEN: string;
    META_WEBHOOK_SECRET: string;
    META_INSTAGRAM_SCOPES: string;
    AI_DEFAULT_PROVIDER: "gemini" | "openai" | "gemini_live";
    GEMINI_MODEL: string;
    OPENAI_MODEL: string;
    RATE_LIMIT_TTL: number;
    RATE_LIMIT_LIMIT: number;
    WEBHOOK_RATE_LIMIT_LIMIT: number;
    REDIS_PASSWORD?: string | undefined;
    GEMINI_API_KEY?: string | undefined;
    GEMINI_LIVE_WS_ENDPOINT?: string | undefined;
    OPENAI_API_KEY?: string | undefined;
}, {
    NODE_ENV?: "development" | "test" | "production" | undefined;
    PORT?: number | undefined;
    WEB_PORT?: number | undefined;
    API_BASE_URL?: string | undefined;
    FRONTEND_URL?: string | undefined;
    DATABASE_URL?: string | undefined;
    REDIS_URL?: string | undefined;
    REDIS_HOST?: string | undefined;
    REDIS_PORT?: number | undefined;
    REDIS_PASSWORD?: string | undefined;
    JWT_SECRET?: string | undefined;
    JWT_EXPIRES_IN?: string | undefined;
    JWT_REFRESH_SECRET?: string | undefined;
    JWT_REFRESH_EXPIRES_IN?: string | undefined;
    COOKIE_SECRET?: string | undefined;
    INSTAGRAM_TOKEN_ENCRYPTION_KEY?: string | undefined;
    META_APP_ID?: string | undefined;
    META_APP_SECRET?: string | undefined;
    META_GRAPH_API_VERSION?: string | undefined;
    META_GRAPH_API_BASE_URL?: string | undefined;
    META_OAUTH_REDIRECT_URI?: string | undefined;
    META_WEBHOOK_VERIFY_TOKEN?: string | undefined;
    META_WEBHOOK_SECRET?: string | undefined;
    META_INSTAGRAM_SCOPES?: string | undefined;
    AI_DEFAULT_PROVIDER?: "gemini" | "openai" | "gemini_live" | undefined;
    GEMINI_API_KEY?: string | undefined;
    GEMINI_MODEL?: string | undefined;
    GEMINI_LIVE_WS_ENDPOINT?: string | undefined;
    OPENAI_API_KEY?: string | undefined;
    OPENAI_MODEL?: string | undefined;
    RATE_LIMIT_TTL?: number | undefined;
    RATE_LIMIT_LIMIT?: number | undefined;
    WEBHOOK_RATE_LIMIT_LIMIT?: number | undefined;
}>;
export type EnvConfig = z.infer<typeof envSchema>;
export declare function getConfig(): EnvConfig;
export declare const config: {
    NODE_ENV: "development" | "test" | "production";
    PORT: number;
    WEB_PORT: number;
    API_BASE_URL: string;
    FRONTEND_URL: string;
    DATABASE_URL: string;
    REDIS_URL: string;
    REDIS_HOST: string;
    REDIS_PORT: number;
    JWT_SECRET: string;
    JWT_EXPIRES_IN: string;
    JWT_REFRESH_SECRET: string;
    JWT_REFRESH_EXPIRES_IN: string;
    COOKIE_SECRET: string;
    INSTAGRAM_TOKEN_ENCRYPTION_KEY: string;
    META_APP_ID: string;
    META_APP_SECRET: string;
    META_GRAPH_API_VERSION: string;
    META_GRAPH_API_BASE_URL: string;
    META_OAUTH_REDIRECT_URI: string;
    META_WEBHOOK_VERIFY_TOKEN: string;
    META_WEBHOOK_SECRET: string;
    META_INSTAGRAM_SCOPES: string;
    AI_DEFAULT_PROVIDER: "gemini" | "openai" | "gemini_live";
    GEMINI_MODEL: string;
    OPENAI_MODEL: string;
    RATE_LIMIT_TTL: number;
    RATE_LIMIT_LIMIT: number;
    WEBHOOK_RATE_LIMIT_LIMIT: number;
    REDIS_PASSWORD?: string | undefined;
    GEMINI_API_KEY?: string | undefined;
    GEMINI_LIVE_WS_ENDPOINT?: string | undefined;
    OPENAI_API_KEY?: string | undefined;
};
